[build]
  command = "npm install && npm run build"
  publish = "dist"
  node_version = "20.11.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"